# Probabilities Stacking

Mean-stack the output probabilities of the current best model for each timestamp to create new predictions

In [2]:
import os
import numpy as np
import pandas as pd
from glob import glob

from config import interim_data_dir

## Mean-stack all test probabilities

In [17]:
files_list = glob(os.path.join(interim_data_dir, 'baseline_probs/test/*.csv'))

data_list = []
for fp in files_list:
    probs_df = pd.read_csv(fp, index_col=0)
    
    data_list.append(probs_df.values)

data = np.stack(data_list)

mean_df = pd.DataFrame(data.mean(axis=0), columns = probs_df.columns)
mean_df.index = probs_df.index.values

mean_df.head()

,crop_id_1,crop_id_2,crop_id_3,crop_id_4,crop_id_5,crop_id_6,crop_id_7,crop_id_8,crop_id_9
5,0.064302,0.205161,0.124695,0.097496,0.203380,0.019232,0.000169,0.080405,0.20516
6,0.064302,0.205161,0.124695,0.097496,0.203380,0.019232,0.000169,0.080405,0.20516
10,0.064302,0.205161,0.124695,0.097496,0.203380,0.019232,0.000169,0.080405,0.20516
18,0.001795,0.000561,0.057114,0.023763,0.010156,0.076282,0.090527,0.598142,0.14166
23,0.000127,0.000592,0.001484,0.063081,0.001135,0.031918,0.102067,0.762946,0.03665

In [18]:
mean_df.to_csv('../../data/submissions/baseline_tpot_mean_stacked.csv')

> Moved up to #1 !

## Median Stacking

In [21]:
median_df = pd.DataFrame(np.median(data, axis=0), columns=probs_df.columns)
median_df.index = probs_df.index.values
median_df.to_csv('../../data/submissions/baseline_tpot_median_stacked.csv')
median_df.head()

,crop_id_1,crop_id_2,crop_id_3,crop_id_4,crop_id_5,crop_id_6,crop_id_7,crop_id_8,crop_id_9
5,0.011364,1.999757e-01,0.109388,0.057399,0.199890,0.002106,0.000061,0.076800,0.199972
6,0.011364,1.999757e-01,0.109388,0.057399,0.199890,0.002106,0.000061,0.076800,0.199972
10,0.011364,1.999757e-01,0.109388,0.057399,0.199890,0.002106,0.000061,0.076800,0.199972
18,0.001355,2.856213e-09,0.041192,0.020022,0.008055,0.071020,0.046253,0.629683,0.148215
23,0.000044,5.493700e-11,0.000422,0.047533,0.000420,0.020262,0.033101,0.839749,0.034821

> Similar to mean stacking but not as good...